# Generated by Django 5.2.8 on 2025-11-29 07:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='release_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
