# Generated by Django 5.2.8 on 2025-11-29 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_set_default_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='genre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
