# Generated by Django 5.2.8 on 2025-11-29 19:50

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_track_file'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='payout',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', Decimal('1.0')), ('amount__lte', Decimal('999999.99'))), name='payout_amount_valid_range'),
        ),
    ]
