# Generated by Django 5.2.8 on 2025-11-30 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_payout_payout_amount_valid_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='payout_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total amount to distribute to collaborators', max_digits=10),
        ),
    ]
