# Generated by Django 5.2.8 on 2025-12-02 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_add_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='processed_streams',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='track',
            name='rate_per_stream',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True),
        ),
    ]
