from rest_framework import viewsets, permissions
from backend.models import Royalty
from api.serializers.track import RoyaltyDetailSerializer


class RoyaltyViewSet(viewsets.ReadOnlyModelViewSet):
    """
    Read-only access to royalties (system-generated only)
    - GET /api/royalties/ - List all royalties for your tracks
    - GET /api/royalties/{id}/ - Get royalty details
    
    Royalties are automatically generated by the system through the royalty service.
    Users cannot manually create or modify royalties.
    """
    serializer_class = RoyaltyDetailSerializer
    permission_classes = [permissions.IsAuthenticated]

    def get_queryset(self):
        """Users see royalties only for their tracks"""
        user = self.request.user
        if user.is_staff:
            return Royalty.objects.all()
        return Royalty.objects.filter(track__owner=user)
